
import { MapNode, WorldMapDefinition, ResourceType } from '../../../types';

const verdantPlainsTanneryOutpostNodes: MapNode[] = [
  {
    id: 'tannery_outpost_entry',
    name: 'Path to Verdant Plains',
    x: 50,
    y: 95,
    iconName: 'ARROW_DOWN',
    description: 'The path leading back to the Verdant Plains.',
    connections: ['tannery_outpost_path_1'],
    poiType: 'MAP_PORTAL',
    targetMapId: 'verdant_plains',
    targetNodeId: 'tannery_guardians',
  },
  {
    id: 'tannery_outpost_path_1',
    name: 'Forest Edge',
    x: 50,
    y: 80,
    iconName: 'COMPASS',
    description: 'The edge of the forest where the tannery is hidden.',
    connections: ['tannery_outpost_entry', 'tannery_battle_1'],
  },
  {
    id: 'tannery_battle_1',
    name: 'Forest Prowlers',
    x: 50,
    y: 65,
    iconName: 'ENEMY',
    description: 'Wolves and spiders guard the outer perimeter.',
    connections: ['tannery_outpost_path_1', 'tannery_choice_1'],
    isBattleNode: true,
    customWaveDefinitionIds: ['map_tannery_battle_1_wave_1', 'map_tannery_battle_1_wave_2'],
  },
  {
    id: 'tannery_choice_1',
    name: 'Hunter\'s Blind',
    x: 50,
    y: 50,
    iconName: 'COMPASS',
    description: 'An old hunter\'s blind. One path leads to a drying rack, the other towards the main building.',
    connections: ['tannery_battle_1', 'tannery_optional_loot_1', 'tannery_path_2'],
    poiType: 'EVENT',
  },
  {
    id: 'tannery_optional_loot_1',
    name: 'Scrap Leather Pile',
    x: 30,
    y: 50,
    iconName: 'LOOT_BAG',
    description: 'A pile of discarded leather scraps, some still usable.',
    connections: ['tannery_choice_1'],
    poiType: 'RESOURCE',
    resourceType: ResourceType.LEATHER,
    resourceAmount: 10,
  },
  {
    id: 'tannery_path_2',
    name: 'Tannery Yard',
    x: 70,
    y: 50,
    iconName: 'COMPASS',
    description: 'The main yard of the tannery.',
    connections: ['tannery_choice_1', 'tannery_battle_2'],
  },
  {
    id: 'tannery_battle_2',
    name: 'Outpost Thugs',
    x: 70,
    y: 35,
    iconName: 'ENEMY',
    description: 'Bandits have claimed the tannery for themselves.',
    connections: ['tannery_path_2', 'tannery_choice_2'],
    isBattleNode: true,
    customWaveDefinitionIds: ['map_tannery_battle_2_wave_1', 'map_tannery_battle_2_wave_2', 'map_tannery_battle_2_wave_3'],
  },
  {
    id: 'tannery_choice_2',
    name: 'Workshop Entrance',
    x: 70,
    y: 20,
    iconName: 'COMPASS',
    description: 'The entrance to the main workshop. A stack of cured hides is nearby.',
    connections: ['tannery_battle_2', 'tannery_optional_loot_2', 'tannery_path_3'],
    poiType: 'EVENT',
  },
  {
    id: 'tannery_optional_loot_2',
    name: 'Cured Hides',
    x: 90,
    y: 20,
    iconName: 'LEATHER',
    description: 'A small stack of well-cured hides.',
    connections: ['tannery_choice_2'],
    poiType: 'RESOURCE',
    resourceType: ResourceType.LEATHER,
    resourceAmount: 15,
  },
  {
    id: 'tannery_path_3',
    name: 'To the Master Tanner\'s Ledger',
    x: 50,
    y: 20,
    iconName: 'COMPASS',
    description: 'A hidden office where the tanner\'s ledger and blueprints are kept.',
    connections: ['tannery_choice_2', 'tannery_battle_3_blueprint'],
  },
  {
    id: 'tannery_battle_3_blueprint',
    name: 'Outpost Leader',
    x: 50,
    y: 5,
    iconName: 'FIGHT',
    description: 'The leader of the bandits holds the Tannery Blueprints.',
    connections: ['tannery_path_3'],
    isBattleNode: true,
    customWaveDefinitionIds: ['map_tannery_battle_3_wave_1', 'map_tannery_battle_3_wave_2', 'map_tannery_battle_3_wave_3', 'map_tannery_battle_3_wave_4'],
  },
];

export const VERDANT_PLAINS_TANNERY_OUTPOST_MAP: WorldMapDefinition = {
  id: 'verdant_plains_tannery_outpost_map',
  name: 'Tannery Outpost',
  description: 'A secluded outpost where the art of leatherworking is practiced.',
  nodes: verdantPlainsTanneryOutpostNodes,
  entryNodeId: 'tannery_outpost_entry',
};
