
import { MapNode, WorldMapDefinition, ResourceType } from '../../../types';

const verdantPlainsFarmsteadRuinsNodes: MapNode[] = [
  {
    id: 'fsr_entry',
    name: 'Trail to Plains',
    x: 50,
    y: 95,
    iconName: 'ARROW_DOWN',
    description: 'The trail leading back to the Verdant Plains.',
    connections: ['fsr_path_1'],
    poiType: 'MAP_PORTAL',
    targetMapId: 'verdant_plains',
    targetNodeId: 'farm_portal',
  },
  {
    id: 'fsr_path_1',
    name: 'Overgrown Fields',
    x: 50,
    y: 80,
    iconName: 'COMPASS',
    description: 'Tall grass obscures the path to the ruined farmstead.',
    connections: ['fsr_entry', 'fsr_battle_1'],
  },
  {
    id: 'fsr_battle_1',
    name: 'Field Pests',
    x: 50,
    y: 65,
    iconName: 'ENEMY',
    description: 'Wild animals have made these fields their home.',
    connections: ['fsr_path_1', 'fsr_choice_1'],
    isBattleNode: true,
    customWaveDefinitionIds: ['map_fsr_battle_1_wave_1', 'map_fsr_battle_1_wave_2'],
  },
  {
    id: 'fsr_choice_1',
    name: 'Collapsed Barn',
    x: 50,
    y: 50,
    iconName: 'COMPASS',
    description: 'A collapsed barn blocks the main path. A small trail leads around it, while another leads into a root cellar.',
    connections: ['fsr_battle_1', 'fsr_optional_loot_1', 'fsr_path_2'],
    poiType: 'EVENT',
  },
  {
    id: 'fsr_optional_loot_1',
    name: 'Root Cellar Cache',
    x: 30,
    y: 50,
    iconName: 'LOOT_BAG',
    description: 'Some preserved foodstuffs, surprisingly intact.',
    connections: ['fsr_choice_1'],
    poiType: 'RESOURCE',
    resourceType: ResourceType.FOOD,
    resourceAmount: 25,
  },
  {
    id: 'fsr_path_2',
    name: 'Farmhouse Approach',
    x: 70,
    y: 50,
    iconName: 'COMPASS',
    description: 'The path leads towards the main farmhouse ruins.',
    connections: ['fsr_choice_1', 'fsr_battle_2'],
  },
  {
    id: 'fsr_battle_2',
    name: 'Farmstead Squatters',
    x: 70,
    y: 35,
    iconName: 'ENEMY',
    description: 'Bandits have taken up residence in the farmhouse ruins.',
    connections: ['fsr_path_2', 'fsr_choice_2'],
    isBattleNode: true,
    customWaveDefinitionIds: ['map_fsr_battle_2_wave_1', 'map_fsr_battle_2_wave_2', 'map_fsr_battle_2_wave_3'],
  },
  {
    id: 'fsr_choice_2',
    name: 'Scholar\'s Study',
    x: 70,
    y: 20,
    iconName: 'COMPASS',
    description: 'The main farmhouse. A faint light emanates from a side room, likely the old study.',
    connections: ['fsr_battle_2', 'fsr_optional_loot_2', 'fsr_path_3'],
    poiType: 'EVENT',
  },
  {
    id: 'fsr_optional_loot_2',
    name: 'Abandoned Study',
    x: 90,
    y: 20,
    iconName: 'LOOT_BAG',
    description: 'Dusty tomes and some meager supplies.',
    connections: ['fsr_choice_2'],
    poiType: 'RESOURCE',
    resourceType: ResourceType.FOOD,
    resourceAmount: 40,
  },
  {
    id: 'fsr_path_3',
    name: 'To the Hidden Library',
    x: 50,
    y: 20,
    iconName: 'COMPASS',
    description: 'A secret passage reveals a hidden library where the almanac might be kept.',
    connections: ['fsr_choice_2', 'fsr_battle_3_blueprint'],
  },
  {
    id: 'fsr_battle_3_blueprint',
    name: 'Protectors of the Almanac',
    x: 50,
    y: 5,
    iconName: 'FIGHT',
    description: 'Ancient spirits guard the farming almanac. Defeat them to claim it.',
    connections: ['fsr_path_3'],
    isBattleNode: true,
    customWaveDefinitionIds: ['map_fsr_battle_3_wave_1', 'map_fsr_battle_3_wave_2', 'map_fsr_battle_3_wave_3', 'map_fsr_battle_3_wave_4'],
  },
];

export const VERDANT_PLAINS_FARMSTEAD_RUINS_MAP: WorldMapDefinition = {
  id: 'verdant_plains_farmstead_ruins',
  name: 'Abandoned Farmstead Ruins',
  description: 'The crumbling remains of an old farmstead, where valuable farming knowledge might be found.',
  nodes: verdantPlainsFarmsteadRuinsNodes,
  entryNodeId: 'fsr_entry',
};
