
import { MapNode, WorldMapDefinition, ResourceType } from '../../../types';

const verdantPlainsNodes: MapNode[] = [
  {
    id: 'hometown',
    name: 'Hometown',
    x: 10, 
    y: 50,
    iconName: 'BUILDING',
    description: 'Your starting point.',
    connections: ['goblin_camp_early'],
  },
  {
    id: 'goblin_camp_early',
    name: 'Early Goblin Camp',
    x: 25,
    y: 50,
    iconName: 'ENEMY',
    description: 'A small goblin encampment blocking the path forward.',
    connections: ['hometown', 'wood_clearing'],
    isBattleNode: true,
    customWaveDefinitionIds: [
      'map_goblin_camp_wave_1', 
      'map_goblin_camp_wave_2', 
      'map_goblin_camp_wave_3', 
      'map_goblin_camp_wave_4'
    ],
  },
  {
    id: 'wood_clearing',
    name: 'Wooded Clearing',
    x: 40,
    y: 50,
    iconName: 'WOOD',
    description: 'A small clearing with some harvestable wood. Resources found here may attract new allies.',
    connections: ['goblin_camp_early', 'lumber_mill_portal', 'farm_portal'],
    poiType: 'RESOURCE',
    resourceType: ResourceType.WOOD,
    resourceAmount: 10,
  },
  {
    id: 'lumber_mill_portal', 
    name: 'Path to Old Lumber Mill', 
    x: 55,
    y: 35, 
    iconName: 'PORTAL', 
    description: 'An overgrown path leading to what looks like an abandoned lumber mill site.', 
    connections: ['wood_clearing', 'gold_mine_access_battle'],
    poiType: 'MAP_PORTAL', 
    targetMapId: 'verdant_plains_lumber_mill_site', 
    targetNodeId: 'lms_entry', 
    isBattleNode: false, 
    customWaveDefinitionIds: undefined, 
  },
  {
    id: 'farm_portal', 
    name: 'Trail to Abandoned Farmstead', 
    x: 55,
    y: 65, 
    iconName: 'PORTAL', 
    description: 'A faint trail winds towards some dilapidated farm buildings.', 
    connections: ['wood_clearing', 'gold_mine_access_battle'],
    poiType: 'MAP_PORTAL', 
    targetMapId: 'verdant_plains_farmstead_ruins', 
    targetNodeId: 'fsr_entry', 
    isBattleNode: false, 
    customWaveDefinitionIds: undefined, 
  },
  {
    id: 'gold_mine_access_battle',
    name: 'Gold Mine Approach',
    x: 70,
    y: 50, 
    iconName: 'FIGHT',
    description: 'A final challenge before reaching the gold-rich mountains.',
    connections: ['lumber_mill_portal', 'farm_portal', 'damaged_gold_mine'], 
    isBattleNode: true,
    battleWaveStart: 3, 
    battleWaveEnd: 4,
  },
  {
    id: 'damaged_gold_mine',
    name: 'Damaged Gold Mine',
    x: 85,
    y: 50,
    iconName: 'PICKAXE_ICON',
    description: 'An old gold mine. A passage seems to lead deeper within.',
    connections: ['gold_mine_access_battle', 'quarry_approach', 'tannery_guardians', 'to_whispering_woods_portal'],
    poiType: 'MAP_PORTAL', 
    targetMapId: 'gold_mine_depths_map',
    targetNodeId: 'gmd_entry',
  },
  {
    id: 'to_whispering_woods_portal', 
    name: 'Path to Whispering Woods',
    x: 85, 
    y: 30, 
    iconName: 'PORTAL',
    description: 'A path leading into the eerie Whispering Woods.',
    connections: ['damaged_gold_mine'], 
    poiType: 'MAP_PORTAL',
    targetMapId: 'wispering_woods_path_edge_map', // Changed targetMapId
    targetNodeId: 'ww_edge_entry',             // Changed targetNodeId
  },
  {
    id: 'tannery_guardians', 
    name: 'Path to Tannery Outpost',
    x: 85, 
    y: 70,
    iconName: 'PORTAL', 
    description: 'A hidden path leading to a secluded tannery. Venture forth to learn the secrets of leatherworking.',
    connections: ['damaged_gold_mine'], 
    poiType: 'MAP_PORTAL', 
    targetMapId: 'verdant_plains_tannery_outpost_map', 
    targetNodeId: 'tannery_outpost_entry', 
    isBattleNode: false, 
  },
  {
    id: 'quarry_approach',
    name: 'Quarry Approach',
    x: 70, 
    y: 90, 
    iconName: 'STONE', 
    description: 'A rocky path leading towards a potential stone quarry.',
    connections: ['damaged_gold_mine', 'stone_quarry_guards'],
  },
  {
    id: 'stone_quarry_guards',
    name: 'Stone Quarry Entrance', 
    x: 55, 
    y: 90,
    iconName: 'PORTAL', 
    description: 'The entrance to a deeper section of the stone quarry. What lies within?',
    connections: ['quarry_approach'],
    poiType: 'MAP_PORTAL', 
    targetMapId: 'stone_quarry_excavation_map',
    targetNodeId: 'sqe_entry',
    isBattleNode: false, 
  },
];

export const VERDANT_PLAINS_MAP: WorldMapDefinition = {
  id: 'verdant_plains',
  name: 'The Verdant Plains',
  description: 'A vast expanse of green fields and scattered copses, charting your first steps into adventure.',
  nodes: verdantPlainsNodes,
  entryNodeId: 'hometown',
};
