
import { MapNode, WorldMapDefinition, ResourceType } from '../../../types';

const stoneQuarryExcavationNodes: MapNode[] = [
  {
    id: 'sqe_entry',
    name: 'Quarry Entrance (Surface)',
    x: 50,
    y: 95,
    iconName: 'ARROW_UP',
    description: 'The path leading back to the quarry approach.',
    connections: ['sqe_path_1'],
    poiType: 'MAP_PORTAL',
    targetMapId: 'verdant_plains',
    targetNodeId: 'stone_quarry_guards',
  },
  {
    id: 'sqe_path_1',
    name: 'Crumbled Walkway',
    x: 50,
    y: 80,
    iconName: 'COMPASS',
    description: 'A precarious walkway deeper into the quarry.',
    connections: ['sqe_entry', 'sqe_battle_1'],
  },
  {
    id: 'sqe_battle_1',
    name: 'Quarry Prowlers',
    x: 50,
    y: 65,
    iconName: 'ENEMY',
    description: 'Beasts that have taken shelter in the upper quarry levels.',
    connections: ['sqe_path_1', 'sqe_choice_1'],
    isBattleNode: true,
    customWaveDefinitionIds: ['map_sqe_battle_1_wave_1', 'map_sqe_battle_1_wave_2'],
  },
  {
    id: 'sqe_choice_1',
    name: 'Dusty Alcove',
    x: 50,
    y: 50,
    iconName: 'COMPASS',
    description: 'An alcove branches off. One path seems to lead to a geode cluster, the other further down.',
    connections: ['sqe_battle_1', 'sqe_optional_loot_1', 'sqe_path_2'],
    poiType: 'EVENT',
  },
  {
    id: 'sqe_optional_loot_1', // Was sqe_geode_discovery
    name: 'Large Geode Cluster',
    x: 30,
    y: 50,
    iconName: 'CRYSTALS',
    description: 'A cluster of geodes, some containing valuable crystals.',
    connections: ['sqe_choice_1'],
    poiType: 'RESOURCE',
    resourceType: ResourceType.CRYSTALS,
    resourceAmount: 10,
    grantsShardId: 'HEALTH_SHARD_BASIC', // Kept shard
    grantsShardLevel: 1,
  },
  {
    id: 'sqe_path_2',
    name: 'Lower Quarry Path',
    x: 70,
    y: 50,
    iconName: 'COMPASS',
    description: 'The path descends into the lower, more dangerous parts of the quarry.',
    connections: ['sqe_choice_1', 'sqe_battle_2'],
  },
  {
    id: 'sqe_battle_2',
    name: 'Excavation Guardians',
    x: 70,
    y: 35,
    iconName: 'ENEMY',
    description: 'Tougher creatures guard the deeper excavation sites.',
    connections: ['sqe_path_2', 'sqe_choice_2'],
    isBattleNode: true,
    customWaveDefinitionIds: ['map_sqe_battle_2_wave_1', 'map_sqe_battle_2_wave_2', 'map_sqe_battle_2_wave_3'],
  },
  {
    id: 'sqe_choice_2',
    name: 'Abandoned Tool Shed',
    x: 70,
    y: 20,
    iconName: 'COMPASS',
    description: 'An old tool shed stands near the blueprint vault. A narrow tunnel branches off.',
    connections: ['sqe_battle_2', 'sqe_optional_loot_2', 'sqe_path_3'],
    poiType: 'EVENT',
  },
  {
    id: 'sqe_optional_loot_2', // Was sqe_unstable_tunnel
    name: 'Iron Deposit',
    x: 90,
    y: 20,
    iconName: 'IRON',
    description: 'A small but rich iron deposit in an unstable tunnel.',
    connections: ['sqe_choice_2'],
    poiType: 'RESOURCE',
    resourceType: ResourceType.IRON,
    resourceAmount: 15,
  },
  {
    id: 'sqe_path_3',
    name: 'To the Blueprint Vault',
    x: 50,
    y: 20,
    iconName: 'COMPASS',
    description: 'The final passage to the quarry\'s blueprint vault.',
    connections: ['sqe_choice_2', 'sqe_battle_3_blueprint'],
  },
  {
    id: 'sqe_battle_3_blueprint', // Was sqe_blueprint_battle
    name: 'Quarry Masters',
    x: 50,
    y: 5,
    iconName: 'FIGHT',
    description: 'The spirits of the original quarry masters protect their designs.',
    connections: ['sqe_path_3'],
    isBattleNode: true,
    customWaveDefinitionIds: ['map_sqe_battle_3_wave_1', 'map_sqe_battle_3_wave_2', 'map_sqe_battle_3_wave_3', 'map_sqe_battle_3_wave_4'],
  },
];

export const STONE_QUARRY_EXCAVATION_MAP: WorldMapDefinition = {
  id: 'stone_quarry_excavation_map',
  name: 'Stone Quarry - Deep Excavation',
  description: 'Delving deeper into the stone quarry reveals new challenges.',
  nodes: stoneQuarryExcavationNodes,
  entryNodeId: 'sqe_entry',
};
