
import { MapNode, WorldMapDefinition, ResourceType } from '../../../types';

const goldMineDepthsNodes: MapNode[] = [
  {
    id: 'gmd_entry',
    name: 'Mine Entrance (Upper)',
    x: 50,
    y: 95,
    iconName: 'ARROW_UP',
    description: 'The passage back to the upper mine area.',
    connections: ['gmd_path_1'],
    poiType: 'MAP_PORTAL',
    targetMapId: 'verdant_plains',
    targetNodeId: 'damaged_gold_mine',
  },
  {
    id: 'gmd_path_1',
    name: 'Main Shaft',
    x: 50,
    y: 80,
    iconName: 'COMPASS',
    description: 'The main shaft descends deeper into the earth.',
    connections: ['gmd_entry', 'gmd_battle_1'],
  },
  {
    id: 'gmd_battle_1',
    name: 'Cave-in Guardians',
    x: 50,
    y: 65,
    iconName: 'ENEMY',
    description: 'Creatures that have made their home in a recently collapsed section.',
    connections: ['gmd_path_1', 'gmd_choice_1'],
    isBattleNode: true,
    customWaveDefinitionIds: ['map_gmd_battle_1_wave_1', 'map_gmd_battle_1_wave_2'],
  },
  {
    id: 'gmd_choice_1',
    name: 'Tunnel Intersection',
    x: 50,
    y: 50,
    iconName: 'COMPASS',
    description: 'The tunnel splits. One path glitters faintly, the other seems to lead to an old storage area.',
    connections: ['gmd_battle_1', 'gmd_optional_loot_1', 'gmd_path_2'],
    poiType: 'EVENT',
  },
  {
    id: 'gmd_optional_loot_1', // Was gmd_crystal_vein
    name: 'Glimmering Crystal Vein',
    x: 30,
    y: 50,
    iconName: 'CRYSTALS',
    description: 'A rich vein of crystals, and some loose gold ore.',
    connections: ['gmd_choice_1'],
    poiType: 'RESOURCE',
    resourceType: ResourceType.GOLD_ORE, // Changed to GOLD_ORE as primary
    resourceAmount: 15,
    grantsShardId: 'DEFENSE_SHARD_BASIC', // Kept shard
    grantsShardLevel: 1,
  },
  {
    id: 'gmd_path_2',
    name: 'Worker\'s Passage',
    x: 70,
    y: 50,
    iconName: 'COMPASS',
    description: 'This passage was likely used by the miners.',
    connections: ['gmd_choice_1', 'gmd_battle_2'],
  },
  {
    id: 'gmd_battle_2',
    name: 'Deep Tunnel Patrol',
    x: 70,
    y: 35,
    iconName: 'ENEMY',
    description: 'Stronger foes patrol these deeper tunnels.',
    connections: ['gmd_path_2', 'gmd_choice_2'],
    isBattleNode: true,
    customWaveDefinitionIds: ['map_gmd_battle_2_wave_1', 'map_gmd_battle_2_wave_2', 'map_gmd_battle_2_wave_3'],
  },
  {
    id: 'gmd_choice_2',
    name: 'Foreman\'s Overlook',
    x: 70,
    y: 20,
    iconName: 'COMPASS',
    description: 'An overlook near what appears to be the main vault. A collapsed section might hide something.',
    connections: ['gmd_battle_2', 'gmd_optional_loot_2', 'gmd_path_3'],
    poiType: 'EVENT',
  },
  {
    id: 'gmd_optional_loot_2', // Was gmd_collapsed_passage
    name: 'Collapsed Storage',
    x: 90,
    y: 20,
    iconName: 'STONE',
    description: 'A small cache of stone and tools, likely from a collapsed storage area.',
    connections: ['gmd_choice_2'],
    poiType: 'RESOURCE',
    resourceType: ResourceType.STONE,
    resourceAmount: 75,
  },
  {
    id: 'gmd_path_3',
    name: 'Path to the Vault',
    x: 50,
    y: 20,
    iconName: 'COMPASS',
    description: 'The final passage to the mine\'s vault where the blueprints are kept.',
    connections: ['gmd_choice_2', 'gmd_battle_3_blueprint'],
  },
  {
    id: 'gmd_battle_3_blueprint', // Was gmd_blueprint_battle
    name: 'Mine Foremen',
    x: 50,
    y: 5,
    iconName: 'FIGHT',
    description: 'The ghostly foremen of this mine guard its original plans.',
    connections: ['gmd_path_3'],
    isBattleNode: true,
    customWaveDefinitionIds: ['map_gmd_battle_3_wave_1', 'map_gmd_battle_3_wave_2', 'map_gmd_battle_3_wave_3', 'map_gmd_battle_3_wave_4'],
  },
];

export const GOLD_MINE_DEPTHS_MAP: WorldMapDefinition = {
  id: 'gold_mine_depths_map',
  name: 'Gold Mine - Deeper Depths',
  description: 'Further exploration into the abandoned gold mine.',
  nodes: goldMineDepthsNodes,
  entryNodeId: 'gmd_entry',
};
