
import { MapNode, WorldMapDefinition, ResourceType } from '../../../types';

const verdantPlainsLumberMillSiteNodes: MapNode[] = [
  {
    id: 'lms_entry',
    name: 'Path to Plains',
    x: 50,
    y: 95, // Start further down
    iconName: 'ARROW_DOWN',
    description: 'The path leading back to the Verdant Plains.',
    connections: ['lms_path_1'],
    poiType: 'MAP_PORTAL',
    targetMapId: 'verdant_plains',
    targetNodeId: 'lumber_mill_portal',
  },
  {
    id: 'lms_path_1',
    name: 'Worn Trail',
    x: 50,
    y: 80,
    iconName: 'COMPASS',
    description: 'A barely visible trail heads towards the old mill.',
    connections: ['lms_entry', 'lms_battle_1'],
  },
  {
    id: 'lms_battle_1',
    name: 'Mill Outskirts Sentinels',
    x: 50,
    y: 65,
    iconName: 'ENEMY',
    description: 'Feral creatures guard the approaches to the mill.',
    connections: ['lms_path_1', 'lms_choice_1'],
    isBattleNode: true,
    customWaveDefinitionIds: ['map_lms_battle_1_wave_1', 'map_lms_battle_1_wave_2'],
  },
  {
    id: 'lms_choice_1',
    name: 'Fork in the Path',
    x: 50,
    y: 50,
    iconName: 'COMPASS',
    description: 'The path splits. One way leads to a dilapidated shed, the other deeper into the mill complex.',
    connections: ['lms_battle_1', 'lms_optional_loot_1', 'lms_path_2'],
    poiType: 'EVENT',
  },
  {
    id: 'lms_optional_loot_1',
    name: 'Rotting Shed',
    x: 30,
    y: 50,
    iconName: 'LOOT_BAG',
    description: 'A few old logs and some forgotten tools.',
    connections: ['lms_choice_1'],
    poiType: 'RESOURCE',
    resourceType: ResourceType.WOOD,
    resourceAmount: 20,
  },
  {
    id: 'lms_path_2',
    name: 'Mill Courtyard Approach',
    x: 70, // To the right from choice
    y: 50,
    iconName: 'COMPASS',
    description: 'The path opens into what was once a courtyard.',
    connections: ['lms_choice_1', 'lms_battle_2'],
  },
  {
    id: 'lms_battle_2',
    name: 'Courtyard Defenders',
    x: 70,
    y: 35,
    iconName: 'ENEMY',
    description: 'More resilient guardians protect the main mill building.',
    connections: ['lms_path_2', 'lms_choice_2'],
    isBattleNode: true,
    customWaveDefinitionIds: ['map_lms_battle_2_wave_1', 'map_lms_battle_2_wave_2', 'map_lms_battle_2_wave_3'],
  },
  {
    id: 'lms_choice_2',
    name: 'Mill Interior Access',
    x: 70,
    y: 20,
    iconName: 'COMPASS',
    description: 'The main mill building looms ahead. A side passage seems to lead to a storage area.',
    connections: ['lms_battle_2', 'lms_optional_loot_2', 'lms_path_3'],
    poiType: 'EVENT',
  },
  {
    id: 'lms_optional_loot_2',
    name: 'Foreman\'s Lost Satchel',
    x: 90,
    y: 20,
    iconName: 'LOOT_BAG',
    description: 'A forgotten satchel, perhaps containing something useful.',
    connections: ['lms_choice_2'],
    poiType: 'RESOURCE',
    resourceType: ResourceType.WOOD, // Changed to wood for thematic consistency
    resourceAmount: 35,
  },
  {
    id: 'lms_path_3',
    name: 'To the Sawmill',
    x: 50, 
    y: 20, // Back towards center from choice 2
    iconName: 'COMPASS',
    description: 'The path leads into the heart of the sawmill.',
    connections: ['lms_choice_2', 'lms_battle_3_blueprint'],
  },
  {
    id: 'lms_battle_3_blueprint',
    name: 'Guardians of the Mill Schematics',
    x: 50,
    y: 5,
    iconName: 'FIGHT',
    description: 'The spectral guardians of the mill\'s original schematics. Defeat them to claim the blueprint.',
    connections: ['lms_path_3'],
    isBattleNode: true,
    customWaveDefinitionIds: ['map_lms_battle_3_wave_1', 'map_lms_battle_3_wave_2', 'map_lms_battle_3_wave_3', 'map_lms_battle_3_wave_4'],
  },
];

export const VERDANT_PLAINS_LUMBER_MILL_SITE_MAP: WorldMapDefinition = {
  id: 'verdant_plains_lumber_mill_site',
  name: 'Old Lumber Mill Site',
  description: 'The dilapidated site of an old lumber mill, rumored to hold its construction plans.',
  nodes: verdantPlainsLumberMillSiteNodes,
  entryNodeId: 'lms_entry',
};
