
import { RunBuffDefinition, RunBuffRarity, HeroStats, ResourceType, RunBuffEffect } from '../../types';

export const COMMON_RUN_BUFFS: Record<string, RunBuffDefinition> = {
  'RUN_BUFF_COMMON_ATTACK': {
    id: 'RUN_BUFF_COMMON_ATTACK',
    name: 'Minor Strength',
    description: 'Increases Attack Damage by 5%, plus 1% per Library level.',
    iconName: 'SWORD',
    rarity: RunBuffRarity.COMMON,
    effects: [{ stat: 'damage' as keyof HeroStats, value: 0.05, type: 'PERCENTAGE_ADDITIVE' }],
    maxStacks: 5,
    isBaseUnlocked: true,
    maxLibraryUpgradeLevel: 10,
    libraryUpgradeCostPerLevel: (level) => [{ resource: ResourceType.GOLD, amount: 50 + (level * 20) + Math.floor(Math.pow(level, 1.8) * 8) }],
    libraryEffectsPerUpgradeLevel: (level) => [{ stat: 'damage' as keyof HeroStats, value: 0.01 * level, type: 'PERCENTAGE_ADDITIVE' }],
  },
  'RUN_BUFF_COMMON_HEALTH': {
    id: 'RUN_BUFF_COMMON_HEALTH',
    name: 'Minor Vitality',
    description: 'Increases Max HP by 5%, plus 1% per Library level.',
    iconName: 'SHIELD',
    rarity: RunBuffRarity.COMMON,
    effects: [{ stat: 'maxHp' as keyof HeroStats, value: 0.05, type: 'PERCENTAGE_ADDITIVE' }],
    maxStacks: 5,
    isBaseUnlocked: true,
    maxLibraryUpgradeLevel: 10,
    libraryUpgradeCostPerLevel: (level) => [{ resource: ResourceType.GOLD, amount: 50 + (level * 20) + Math.floor(Math.pow(level, 1.8) * 8) }],
    libraryEffectsPerUpgradeLevel: (level) => [{ stat: 'maxHp' as keyof HeroStats, value: 0.01 * level, type: 'PERCENTAGE_ADDITIVE' }],
  },
  'RUN_BUFF_COMMON_DEFENSE': {
    id: 'RUN_BUFF_COMMON_DEFENSE',
    name: 'Stone Skin',
    description: 'Increases Defense by 2, plus 0.5 per Library level.',
    iconName: 'STONE',
    rarity: RunBuffRarity.COMMON,
    effects: [{ stat: 'defense' as keyof HeroStats, value: 2, type: 'FLAT' }],
    maxStacks: 5,
    isBaseUnlocked: true,
    maxLibraryUpgradeLevel: 10,
    libraryUpgradeCostPerLevel: (level) => [{ resource: ResourceType.STONE, amount: 40 + (level * 15) + Math.floor(Math.pow(level, 1.7) * 7) }],
    libraryEffectsPerUpgradeLevel: (level) => [{ stat: 'defense' as keyof HeroStats, value: 0.5 * level, type: 'FLAT' }],
  },
  'RUN_BUFF_COMMON_CRIT_CHANCE': {
    id: 'RUN_BUFF_COMMON_CRIT_CHANCE',
    name: 'Minor Keen Edge',
    description: 'Increases Crit Chance by 1%, plus 0.2% per Library level.',
    iconName: 'MAGIC_ARROW',
    rarity: RunBuffRarity.COMMON,
    effects: [{ stat: 'critChance' as keyof HeroStats, value: 0.01, type: 'FLAT' }],
    maxStacks: 5,
    isBaseUnlocked: true,
    maxLibraryUpgradeLevel: 10,
    libraryUpgradeCostPerLevel: (level) => [{ resource: ResourceType.GOLD, amount: 75 + (level * 25) }],
    libraryEffectsPerUpgradeLevel: (level) => [{ stat: 'critChance' as keyof HeroStats, value: 0.002 * level, type: 'FLAT' }],
  },
  'RUN_BUFF_COMMON_CRIT_DAMAGE': {
    id: 'RUN_BUFF_COMMON_CRIT_DAMAGE',
    name: 'Minor Savage Strikes',
    description: 'Increases Crit Damage by 5%, plus 1% per Library level.',
    iconName: 'SWORD',
    rarity: RunBuffRarity.COMMON,
    effects: [{ stat: 'critDamage' as keyof HeroStats, value: 0.05, type: 'PERCENTAGE_ADDITIVE' }],
    maxStacks: 5,
    isBaseUnlocked: true,
    maxLibraryUpgradeLevel: 10,
    libraryUpgradeCostPerLevel: (level) => [{ resource: ResourceType.GOLD, amount: 80 + (level * 30)}],
    libraryEffectsPerUpgradeLevel: (level) => [{ stat: 'critDamage' as keyof HeroStats, value: 0.01 * level, type: 'PERCENTAGE_ADDITIVE' }],
  },
  'RUN_BUFF_COMMON_SPEED_BOOST': {
    id: 'RUN_BUFF_COMMON_SPEED_BOOST',
    name: 'Minor Swiftness',
    description: 'Increases Attack Speed by 0.02, plus 0.005 per Library level.',
    iconName: 'WIND_SLASH',
    rarity: RunBuffRarity.COMMON,
    effects: [{ stat: 'attackSpeed' as keyof HeroStats, value: 0.02, type: 'FLAT' }],
    maxStacks: 5,
    isBaseUnlocked: true,
    maxLibraryUpgradeLevel: 10,
    libraryUpgradeCostPerLevel: (level) => [{ resource: ResourceType.GOLD, amount: 60 + (level * 22) }],
    libraryEffectsPerUpgradeLevel: (level) => [{ stat: 'attackSpeed' as keyof HeroStats, value: 0.005 * level, type: 'FLAT' }],
  },
};
