
import { RunBuffDefinition, RunBuffRarity, HeroStats, ResourceType, RunBuffEffect } from '../../types';

export const EPIC_RUN_BUFFS: Record<string, RunBuffDefinition> = {
  'RUN_BUFF_EPIC_ATTACK': {
    id: 'RUN_BUFF_EPIC_ATTACK',
    name: 'Heroic Strength',
    description: 'Increases Attack Damage by 20%, plus 1.75% per Library level.',
    iconName: 'SWORD',
    rarity: RunBuffRarity.EPIC,
    effects: [{ stat: 'damage' as keyof HeroStats, value: 0.20, type: 'PERCENTAGE_ADDITIVE' }],
    maxStacks: 2,
    isBaseUnlocked: false,
    unlockCost: [{ resource: ResourceType.GOLD, amount: 10000 }, { resource: ResourceType.CRYSTALS, amount: 500 }],
    maxLibraryUpgradeLevel: 10,
    libraryUpgradeCostPerLevel: (level) => [{ resource: ResourceType.GOLD, amount: 5000 + (level * 2000) }, { resource: ResourceType.AETHERIUM, amount: 1 + Math.floor(level / 2) }],
    libraryEffectsPerUpgradeLevel: (level) => [{ stat: 'damage' as keyof HeroStats, value: 0.0175 * level, type: 'PERCENTAGE_ADDITIVE' }],
  },
  'RUN_BUFF_EPIC_HEALTH': {
    id: 'RUN_BUFF_EPIC_HEALTH',
    name: 'Heroic Vitality',
    description: 'Increases Max HP by 20%, plus 1.75% per Library level.',
    iconName: 'SHIELD',
    rarity: RunBuffRarity.EPIC,
    effects: [{ stat: 'maxHp' as keyof HeroStats, value: 0.20, type: 'PERCENTAGE_ADDITIVE' }],
    maxStacks: 2,
    isBaseUnlocked: false,
    unlockCost: [{ resource: ResourceType.GOLD, amount: 10000 }, { resource: ResourceType.IRON, amount: 500 }],
    maxLibraryUpgradeLevel: 10,
    libraryUpgradeCostPerLevel: (level) => [{ resource: ResourceType.GOLD, amount: 5000 + (level * 2000) }, { resource: ResourceType.CRYSTALS, amount: 30 + level * 15 }],
    libraryEffectsPerUpgradeLevel: (level) => [{ stat: 'maxHp' as keyof HeroStats, value: 0.0175 * level, type: 'PERCENTAGE_ADDITIVE' }],
  },
  'RUN_BUFF_EPIC_DEFENSE': {
    id: 'RUN_BUFF_EPIC_DEFENSE',
    name: 'Adamant Skin',
    description: 'Increases Defense by 8, plus 1.25 per Library level.',
    iconName: 'STONE',
    rarity: RunBuffRarity.EPIC,
    effects: [{ stat: 'defense' as keyof HeroStats, value: 8, type: 'FLAT' }],
    maxStacks: 2,
    isBaseUnlocked: false,
    unlockCost: [{ resource: ResourceType.CRYSTALS, amount: 800 }, { resource: ResourceType.AETHERIUM, amount: 2 }],
    maxLibraryUpgradeLevel: 10,
    libraryUpgradeCostPerLevel: (level) => [{ resource: ResourceType.CRYSTALS, amount: 400 + (level * 150) }, { resource: ResourceType.AETHERIUM, amount: 1 + Math.floor(level / 2.5) }],
    libraryEffectsPerUpgradeLevel: (level) => [{ stat: 'defense' as keyof HeroStats, value: 1.25 * level, type: 'FLAT' }],
  },
  'RUN_BUFF_EPIC_CRIT_CHANCE': {
    id: 'RUN_BUFF_EPIC_CRIT_CHANCE',
    name: 'Lethal Focus',
    description: 'Increases Crit Chance by 4%, plus 0.5% per Library level.',
    iconName: 'MAGIC_ARROW',
    rarity: RunBuffRarity.EPIC,
    effects: [{ stat: 'critChance' as keyof HeroStats, value: 0.04, type: 'FLAT' }],
    maxStacks: 2,
    isBaseUnlocked: false,
    unlockCost: [{ resource: ResourceType.GOLD, amount: 12000 }, { resource: ResourceType.CRYSTALS, amount: 600 }, { resource: ResourceType.AETHERIUM, amount: 1 }],
    maxLibraryUpgradeLevel: 10,
    libraryUpgradeCostPerLevel: (level) => [{ resource: ResourceType.GOLD, amount: 6000 + (level * 2500) }, { resource: ResourceType.AETHERIUM, amount: 1 + Math.floor(level / 2.8) }],
    libraryEffectsPerUpgradeLevel: (level) => [{ stat: 'critChance' as keyof HeroStats, value: 0.005 * level, type: 'FLAT' }],
  },
  'RUN_BUFF_EPIC_CRIT_DAMAGE': {
    id: 'RUN_BUFF_EPIC_CRIT_DAMAGE',
    name: 'Decimating Strikes',
    description: 'Increases Crit Damage by 20%, plus 1.75% per Library level.',
    iconName: 'SWORD',
    rarity: RunBuffRarity.EPIC,
    effects: [{ stat: 'critDamage' as keyof HeroStats, value: 0.20, type: 'PERCENTAGE_ADDITIVE' }],
    maxStacks: 2,
    isBaseUnlocked: false,
    unlockCost: [{ resource: ResourceType.GOLD, amount: 14000 }, { resource: ResourceType.CRYSTALS, amount: 700 }, {resource: ResourceType.AETHERIUM, amount: 1}],
    maxLibraryUpgradeLevel: 10,
    libraryUpgradeCostPerLevel: (level) => [{ resource: ResourceType.GOLD, amount: 7000 + (level * 3000) }, { resource: ResourceType.AETHERIUM, amount: 1 + Math.floor(level / 2.8) }],
    libraryEffectsPerUpgradeLevel: (level) => [{ stat: 'critDamage' as keyof HeroStats, value: 0.0175 * level, type: 'PERCENTAGE_ADDITIVE' }],
  },
  'RUN_BUFF_EPIC_SPEED_BOOST': {
    id: 'RUN_BUFF_EPIC_SPEED_BOOST',
    name: 'Heroic Swiftness',
    description: 'Increases Attack Speed by 0.10, plus 0.0125 per Library level.',
    iconName: 'WIND_SLASH',
    rarity: RunBuffRarity.EPIC,
    effects: [{ stat: 'attackSpeed' as keyof HeroStats, value: 0.10, type: 'FLAT' }],
    maxStacks: 2,
    isBaseUnlocked: false,
    unlockCost: [{ resource: ResourceType.GOLD, amount: 11000 }, { resource: ResourceType.CRYSTALS, amount: 550 }],
    maxLibraryUpgradeLevel: 10,
    libraryUpgradeCostPerLevel: (level) => [{ resource: ResourceType.GOLD, amount: 5500 + (level * 2200) }, { resource: ResourceType.AETHERIUM, amount: 1 + Math.floor(level / 2.9) }],
    libraryEffectsPerUpgradeLevel: (level) => [{ stat: 'attackSpeed' as keyof HeroStats, value: 0.0125 * level, type: 'FLAT' }],
  },
};
