
import { RunBuffDefinition, RunBuffRarity, HeroStats, ResourceType, RunBuffEffect } from '../../types';

export const UNCOMMON_RUN_BUFFS: Record<string, RunBuffDefinition> = {
  'RUN_BUFF_UNCOMMON_ATTACK': {
    id: 'RUN_BUFF_UNCOMMON_ATTACK',
    name: 'Moderate Strength',
    description: 'Increases Attack Damage by 10%, plus 1.25% per Library level.',
    iconName: 'SWORD',
    rarity: RunBuffRarity.UNCOMMON,
    effects: [{ stat: 'damage' as keyof HeroStats, value: 0.10, type: 'PERCENTAGE_ADDITIVE' }],
    maxStacks: 4,
    isBaseUnlocked: false,
    unlockCost: [{ resource: ResourceType.GOLD, amount: 500 }, { resource: ResourceType.WOOD, amount: 100 }],
    maxLibraryUpgradeLevel: 10,
    libraryUpgradeCostPerLevel: (level) => [{ resource: ResourceType.GOLD, amount: 250 + (level * 100) }, { resource: ResourceType.IRON, amount: 10 + level * 5 }],
    libraryEffectsPerUpgradeLevel: (level) => [{ stat: 'damage' as keyof HeroStats, value: 0.0125 * level, type: 'PERCENTAGE_ADDITIVE' }],
  },
  'RUN_BUFF_UNCOMMON_HEALTH': {
    id: 'RUN_BUFF_UNCOMMON_HEALTH',
    name: 'Moderate Vitality',
    description: 'Increases Max HP by 10%, plus 1.25% per Library level.',
    iconName: 'SHIELD',
    rarity: RunBuffRarity.UNCOMMON,
    effects: [{ stat: 'maxHp' as keyof HeroStats, value: 0.10, type: 'PERCENTAGE_ADDITIVE' }],
    maxStacks: 4,
    isBaseUnlocked: false,
    unlockCost: [{ resource: ResourceType.GOLD, amount: 500 }, { resource: ResourceType.STONE, amount: 100 }],
    maxLibraryUpgradeLevel: 10,
    libraryUpgradeCostPerLevel: (level) => [{ resource: ResourceType.GOLD, amount: 250 + (level * 100) }, { resource: ResourceType.LEATHER, amount: 10 + level * 5 }],
    libraryEffectsPerUpgradeLevel: (level) => [{ stat: 'maxHp' as keyof HeroStats, value: 0.0125 * level, type: 'PERCENTAGE_ADDITIVE' }],
  },
  'RUN_BUFF_UNCOMMON_DEFENSE': {
    id: 'RUN_BUFF_UNCOMMON_DEFENSE',
    name: 'Iron Skin',
    description: 'Increases Defense by 4, plus 0.75 per Library level.',
    iconName: 'STONE',
    rarity: RunBuffRarity.UNCOMMON,
    effects: [{ stat: 'defense' as keyof HeroStats, value: 4, type: 'FLAT' }],
    maxStacks: 4,
    isBaseUnlocked: false,
    unlockCost: [{ resource: ResourceType.STONE, amount: 200 }, { resource: ResourceType.IRON, amount: 50 }],
    maxLibraryUpgradeLevel: 10,
    libraryUpgradeCostPerLevel: (level) => [{ resource: ResourceType.STONE, amount: 200 + (level * 75) }, { resource: ResourceType.IRON, amount: 25 + level * 10 }],
    libraryEffectsPerUpgradeLevel: (level) => [{ stat: 'defense' as keyof HeroStats, value: 0.75 * level, type: 'FLAT' }],
  },
  'RUN_BUFF_UNCOMMON_CRIT_CHANCE': {
    id: 'RUN_BUFF_UNCOMMON_CRIT_CHANCE',
    name: 'Keen Edge',
    description: 'Increases Crit Chance by 2%, plus 0.3% per Library level.',
    iconName: 'MAGIC_ARROW',
    rarity: RunBuffRarity.UNCOMMON,
    effects: [{ stat: 'critChance' as keyof HeroStats, value: 0.02, type: 'FLAT' }],
    maxStacks: 4,
    isBaseUnlocked: false,
    unlockCost: [{ resource: ResourceType.GOLD, amount: 600}, {resource: ResourceType.CRYSTALS, amount: 20}],
    maxLibraryUpgradeLevel: 10,
    libraryUpgradeCostPerLevel: (level) => [{ resource: ResourceType.GOLD, amount: 300 + (level * 120)}, {resource: ResourceType.CRYSTALS, amount: 10 + level * 3}],
    libraryEffectsPerUpgradeLevel: (level) => [{ stat: 'critChance' as keyof HeroStats, value: 0.003 * level, type: 'FLAT' }],
  },
  'RUN_BUFF_UNCOMMON_CRIT_DAMAGE': {
    id: 'RUN_BUFF_UNCOMMON_CRIT_DAMAGE',
    name: 'Savage Strikes',
    description: 'Increases Crit Damage by 10%, plus 1.25% per Library level.',
    iconName: 'SWORD',
    rarity: RunBuffRarity.UNCOMMON,
    effects: [{ stat: 'critDamage' as keyof HeroStats, value: 0.10, type: 'PERCENTAGE_ADDITIVE' }],
    maxStacks: 4,
    isBaseUnlocked: false,
    unlockCost: [{ resource: ResourceType.GOLD, amount: 700}, {resource: ResourceType.IRON, amount: 75}],
    maxLibraryUpgradeLevel: 10,
    libraryUpgradeCostPerLevel: (level) => [{ resource: ResourceType.GOLD, amount: 350 + (level * 130)}, {resource: ResourceType.IRON, amount: 30 + level * 10}],
    libraryEffectsPerUpgradeLevel: (level) => [{ stat: 'critDamage' as keyof HeroStats, value: 0.0125 * level, type: 'PERCENTAGE_ADDITIVE' }],
  },
  'RUN_BUFF_UNCOMMON_SPEED_BOOST': {
    id: 'RUN_BUFF_UNCOMMON_SPEED_BOOST',
    name: 'Swiftness Aura',
    description: 'Increases Attack Speed by 0.05, plus 0.0075 per Library level.',
    iconName: 'WIND_SLASH',
    rarity: RunBuffRarity.UNCOMMON,
    effects: [{ stat: 'attackSpeed' as keyof HeroStats, value: 0.05, type: 'FLAT' }],
    maxStacks: 4,
    isBaseUnlocked: false,
    unlockCost: [{ resource: ResourceType.GOLD, amount: 550 }, {resource: ResourceType.WOOD, amount: 120}],
    maxLibraryUpgradeLevel: 10,
    libraryUpgradeCostPerLevel: (level) => [{ resource: ResourceType.GOLD, amount: 275 + (level * 110) }, {resource: ResourceType.LEATHER, amount: 15 + level * 6}],
    libraryEffectsPerUpgradeLevel: (level) => [{ stat: 'attackSpeed' as keyof HeroStats, value: 0.0075 * level, type: 'FLAT' }],
  },
  'RUN_BUFF_SIGHT_RADIUS': {
    id: 'RUN_BUFF_SIGHT_RADIUS',
    name: 'Eagle Eye',
    description: 'Increases dungeon sight radius by 1.',
    iconName: 'COMPASS',
    rarity: RunBuffRarity.UNCOMMON,
    effects: [],
    maxStacks: 1,
    isBaseUnlocked: true,
    unlockCost: [{ resource: ResourceType.GOLD, amount: 500 }, { resource: ResourceType.WOOD, amount: 150 }],
    maxLibraryUpgradeLevel: 0,
  },
};
