export enum MinigameEventType {
  CRYSTAL_SHOWER = 'CRYSTAL_SHOWER',
  ESSENCE_BOOM = 'ESSENCE_BOOM',
  MOLE_ATTACK = 'MOLE_ATTACK',
  GOLEM_FRENZY = 'GOLEM_FRENZY',
  RESOURCE_SURGE = 'RESOURCE_SURGE',
  GEODE_DISCOVERY = 'GEODE_DISCOVERY',
}
