
export enum ResourceType {
  GOLD = 'GOLD',
  WOOD = 'WOOD',
  STONE = 'STONE',
  FOOD = 'FOOD',
  IRON = 'IRON',
  CRYSTALS = 'CRYSTALS', // This is the main game crystal, not the minigame one.
  LEATHER = 'LEATHER',
  TOWN_XP = 'TOWN_XP',
  HEROIC_POINTS = 'HEROIC_POINTS',
  META_CURRENCY = 'META_CURRENCY',
  GUILD_HALL_TOKEN = 'GUILD_HALL_TOKEN',
  CATACOMB_KEY = 'CATACOMB_KEY',
  CATACOMB_BLUEPRINT = 'CATACOMB_BLUEPRINT',
  AETHERIUM = 'AETHERIUM',
  HERB_BLOODTHISTLE = 'HERB_BLOODTHISTLE',
  HERB_IRONWOOD_LEAF = 'HERB_IRONWOOD_LEAF',
  MINIGAME_DIRT = 'MINIGAME_DIRT',
  MINIGAME_CLAY = 'MINIGAME_CLAY',
  MINIGAME_SAND = 'MINIGAME_SAND',
  MINIGAME_ESSENCE = 'MINIGAME_ESSENCE',
  MINIGAME_CRYSTAL = 'MINIGAME_CRYSTAL', // Generic Minigame Crystal
  MINIGAME_EMERALD = 'MINIGAME_EMERALD',
  MINIGAME_RUBY = 'MINIGAME_RUBY',
  MINIGAME_SAPPHIRE = 'MINIGAME_SAPPHIRE',
  GOLD_ORE = 'GOLD_ORE',
  DIAMOND_ORE = 'DIAMOND_ORE',
  EMPTY = 'EMPTY', // Added for Gold Mine Grid
  SKILL_POINTS_TEMP = 'SKILL_POINTS_TEMP', // For utility function
  DIRT = 'DIRT', // Added for Gold Mine Cell Type
  OBSTACLE = 'OBSTACLE', // Added for Gold Mine Cell Type
  DEMONIC_COIN = 'DEMONIC_COIN', // New currency for Demonicon
  RESEARCH_POINTS = 'RESEARCH_POINTS', // New currency for Research
}
