
export const ARENA_WIDTH_UNITS = 768;
export const ARENA_HEIGHT_UNITS = 568;
export const PARTICIPANT_SIZE_UNITS = 32;
export const MOVEMENT_SPEED_UNITS_PER_TICK = 2;
export const RANGED_ATTACK_RANGE_UNITS_DEFAULT = 150;
export const ATTACK_RANGE_UNITS = PARTICIPANT_SIZE_UNITS * 1.5;
export const WAVE_CLEAR_COOLDOWN_TICKS = 100;
export const ATTACK_ANIMATION_TICKS = 10;
export const DEATH_ANIMATION_TICKS = 25;
export const PROJECTILE_SPEED_PER_TICK = 10;
export const PROJECTILE_SIZE_PX = 8;
export const MAX_PROJECTILE_TRAIL_SEGMENTS = 10;
