
import { ResourceType } from '../types';

export const SQMG_GRID_SIZE = 10;
export const SQMG_DIRT_CLICK_YIELD = 1;
export const SQMG_PLAYER_CLICK_POWER_UPGRADE_COST_BASE = 10;
export const SQMG_PLAYER_CLICK_POWER_UPGRADE_COST_FACTOR = 1.5;
export const SQMG_PLAYER_CLICK_POWER_UPGRADE_BONUS = 1;

export const SQMG_DIRT_TO_CLAY_CLICKS = 20;
export const SQMG_CLAY_TO_SAND_CLICKS = 100;

export const SQMG_CELL_COLORS: Record<ResourceType.MINIGAME_DIRT | ResourceType.MINIGAME_CLAY | ResourceType.MINIGAME_SAND, string> = {
  [ResourceType.MINIGAME_DIRT]: 'bg-yellow-700 hover:bg-yellow-600 active:bg-yellow-800 border-yellow-800',
  [ResourceType.MINIGAME_CLAY]: 'bg-stone-500 hover:bg-stone-400 active:bg-stone-600 border-stone-600',
  [ResourceType.MINIGAME_SAND]: 'bg-yellow-300 hover:bg-yellow-200 active:bg-yellow-400 border-yellow-400',
};

export const SQMG_GOLEM_COST_DIRT = 100;
export const SQMG_GOLEM_COST_ESSENCE = 5;
export const SQMG_CLAY_GOLEM_COST_CLAY = 200;
export const SQMG_SAND_GOLEM_COST_SAND = 300;
export const SQMG_SAND_GOLEM_COST_ESSENCE = 15;
export const SQMG_CRYSTAL_GOLEM_COST_EMERALD = 10;
export const SQMG_CRYSTAL_GOLEM_COST_RUBY = 10;
export const SQMG_CRYSTAL_GOLEM_COST_SAPPHIRE = 10;
export const SQMG_CRYSTAL_GOLEM_COST_ESSENCE = 50;

export const SQMG_INITIAL_GOLEM_CLICK_POWER = 1;
export const SQMG_INITIAL_GOLEM_CLICK_SPEED_MS = 2000;
export const SQMG_INITIAL_GOLEM_MOVE_SPEED_MS = 5000;

export const CLAY_GOLEM_CLICK_POWER_MULTIPLIER = 2;
export const CLAY_GOLEM_UPGRADE_BONUS_MULTIPLIER = 2;
export const SAND_GOLEM_CLICK_POWER_MULTIPLIER = 3;
export const SAND_GOLEM_UPGRADE_BONUS_MULTIPLIER = 3;
export const CRYSTAL_GOLEM_CLICK_POWER_MULTIPLIER = 5;
export const CRYSTAL_GOLEM_UPGRADE_BONUS_MULTIPLIER = 5;
export const CRYSTAL_GOLEM_RARE_FIND_BONUS_CHANCE = 0.10;

export const SQMG_GOLEM_COLORS = {
    DIRT: 'text-slate-400',
    CLAY: 'text-orange-500',
    SAND: 'text-yellow-400',
    CRYSTAL: 'text-cyan-400',
    MOLE: 'text-green-500',
};

export const SQMG_GOLEM_CLICK_POWER_UPGRADE_BASE_COST_DIRT = 50;
export const SQMG_GOLEM_CLICK_POWER_UPGRADE_BASE_COST_CLAY = 30;
export const SQMG_GOLEM_CLICK_POWER_UPGRADE_BASE_COST_ESSENCE = 2;
export const SQMG_GOLEM_CLICK_POWER_UPGRADE_BONUS = 1;

export const SQMG_GOLEM_CLICK_SPEED_UPGRADE_BASE_COST_DIRT = 75;
export const SQMG_GOLEM_CLICK_SPEED_UPGRADE_BASE_COST_CLAY = 40;
export const SQMG_GOLEM_CLICK_SPEED_UPGRADE_BASE_COST_ESSENCE = 3;
export const SQMG_GOLEM_CLICK_SPEED_REDUCTION_MS = 200;

export const SQMG_GOLEM_MOVE_SPEED_UPGRADE_BASE_COST_DIRT = 75;
export const SQMG_GOLEM_MOVE_SPEED_UPGRADE_BASE_COST_SAND = 35;
export const SQMG_GOLEM_MOVE_SPEED_UPGRADE_BASE_COST_ESSENCE = 3;
export const SQMG_GOLEM_MOVE_SPEED_REDUCTION_MS = 500;

export const SQMG_ESSENCE_DROP_CHANCE = 0.05;
export const SQMG_ESSENCE_DROP_CHANCE_UPGRADE_BASE_COST_DIRT = 100;
export const SQMG_ESSENCE_DROP_CHANCE_UPGRADE_BASE_COST_SAND = 75;
export const SQMG_ESSENCE_DROP_CHANCE_UPGRADE_BASE_COST_ESSENCE = 10;
export const SQMG_ESSENCE_DROP_CHANCE_UPGRADE_BONUS = 0.01;

export const SQMG_PLAYER_MULTI_CLICK_CHANCE_BASE = 0.0;
export const SQMG_PLAYER_MULTI_CLICK_CHANCE_UPGRADE_BONUS = 0.01;
export const SQMG_PLAYER_MULTI_CLICK_CHANCE_UPGRADE_BASE_COST_DIRT = 200;
export const SQMG_PLAYER_MULTI_CLICK_CHANCE_UPGRADE_BASE_COST_CLAY = 50;
export const SQMG_PLAYER_MULTI_CLICK_CHANCE_UPGRADE_BASE_COST_ESSENCE = 15;
export const SQMG_MAX_PLAYER_MULTI_CLICK_CHANCE = 0.25;

export const SQMG_GOLEM_ESSENCE_AFFINITY_BASE = 0.0;
export const SQMG_GOLEM_ESSENCE_AFFINITY_UPGRADE_BONUS = 0.005;
export const SQMG_GOLEM_ESSENCE_AFFINITY_UPGRADE_BASE_COST_DIRT = 100;
export const SQMG_GOLEM_ESSENCE_AFFINITY_UPGRADE_BASE_COST_CLAY = 150;
export const SQMG_GOLEM_ESSENCE_AFFINITY_UPGRADE_BASE_COST_ESSENCE = 20;
export const SQMG_MAX_GOLEM_ESSENCE_AFFINITY = 0.10;

export const SQMG_CRYSTAL_DROP_CHANCE = 0.02;
export const SQMG_PLAYER_CRYSTAL_FIND_CHANCE_BASE = 0.0;
export const SQMG_PLAYER_CRYSTAL_FIND_CHANCE_UPGRADE_BONUS = 0.005;
export const SQMG_PLAYER_CRYSTAL_FIND_CHANCE_UPGRADE_BASE_COST_DIRT = 100;
export const SQMG_PLAYER_CRYSTAL_FIND_CHANCE_UPGRADE_BASE_COST_SAND = 150;
export const SQMG_PLAYER_CRYSTAL_FIND_CHANCE_UPGRADE_BASE_COST_ESSENCE = 25;
export const SQMG_MAX_PLAYER_CRYSTAL_FIND_CHANCE = 0.15;

export const SQMG_GOLEM_CRYSTAL_SIFTERS_BASE = 0.0;
export const SQMG_GOLEM_CRYSTAL_SIFTERS_UPGRADE_BONUS = 0.0025;
export const SQMG_GOLEM_CRYSTAL_SIFTERS_UPGRADE_BASE_COST_DIRT = 150;
export const SQMG_GOLEM_CRYSTAL_SIFTERS_UPGRADE_BASE_COST_SAND = 200;
export const SQMG_GOLEM_CRYSTAL_SIFTERS_UPGRADE_BASE_COST_ESSENCE = 30;
export const SQMG_MAX_GOLEM_CRYSTAL_SIFTERS = 0.075;

export const SQMG_PLAYER_ADVANCED_EXCAVATION_BASE_CHANCE = 0.0;
export const SQMG_PLAYER_ADVANCED_EXCAVATION_UPGRADE_BONUS = 0.002;
export const SQMG_PLAYER_ADVANCED_EXCAVATION_UPGRADE_BASE_COST_SAND = 200;
export const SQMG_PLAYER_ADVANCED_EXCAVATION_UPGRADE_BASE_COST_CRYSTAL = 10;
export const SQMG_MAX_PLAYER_ADVANCED_EXCAVATION_CHANCE = 0.10;

export const SQMG_EMERALD_EXPERTISE_UPGRADE_BONUS = 0.001;
export const SQMG_EMERALD_EXPERTISE_UPGRADE_BASE_COST_DIRT = 1000;
export const SQMG_EMERALD_EXPERTISE_UPGRADE_BASE_COST_ESSENCE = 20;

export const SQMG_RUBY_REFINEMENT_UPGRADE_BONUS = 0.001;
export const SQMG_RUBY_REFINEMENT_UPGRADE_BASE_COST_CLAY = 800;
export const SQMG_RUBY_REFINEMENT_UPGRADE_BASE_COST_ESSENCE = 25;
export const SQMG_RUBY_REFINEMENT_UPGRADE_BASE_COST_EMERALD = 5;

export const SQMG_SAPPHIRE_SYNTHESIS_UPGRADE_BONUS = 0.001;
export const SQMG_SAPPHIRE_SYNTHESIS_UPGRADE_BASE_COST_SAND = 600;
export const SQMG_SAPPHIRE_SYNTHESIS_UPGRADE_BASE_COST_ESSENCE = 30;
export const SQMG_SAPPHIRE_SYNTHESIS_UPGRADE_BASE_COST_RUBY = 5;

export const SQMG_EMERALD_DROP_CHANCE_FROM_SAND = 0.005;
export const SQMG_RUBY_DROP_CHANCE_FROM_SAND = 0.004;
export const SQMG_SAPPHIRE_DROP_CHANCE_FROM_SAND = 0.003;

export const SQMG_UPGRADE_COST_SCALING_FACTOR = 1.2;
export const SQMG_MIN_GOLEM_CLICK_SPEED_MS = 500;
export const SQMG_MIN_GOLEM_MOVE_SPEED_MS = 1000;
export const SQMG_MAX_ESSENCE_DROP_CHANCE = 0.5;

export const SQMG_EVENT_TRIGGER_CHANCE_PER_TICK = 0.0005;
export const SQMG_EVENT_BASE_DURATION_TICKS = 500;
export const SQMG_CRYSTAL_SHOWER_BONUS_CHANCE = 0.25;
export const SQMG_ESSENCE_BOOM_BONUS_CHANCE = 0.30;
export const SQMG_MOLE_ATTACK_MIN_MOLES = 1;
export const SQMG_MOLE_ATTACK_MAX_MOLES = 10;
export const SQMG_MOLE_MOVE_COOLDOWN_MS = 250;
export const SQMG_MOLE_ACTION_COOLDOWN_MS = 1000;
export const SQMG_MOLE_ATTACK_DURATION_TICKS = 750;
