
import { DungeonEventDefinition } from '../types';

// Import individual event definitions
import { SHRINE_OF_EMPOWERMENT_T1_DEFINITION } from './events/shrineOfEmpowermentT1';
import { HIDDEN_CACHE_TIER1_DEFINITION } from './events/hiddenCacheT1';
import { EERIE_SOUNDS_TIER1_DEFINITION } from './events/eerieSoundsT1';
import { OLD_DIARY_TIER1_DEFINITION } from './events/oldDiaryT1';
import { FOUNTAIN_OF_CHOICE_T1_DEFINITION } from './events/fountainOfChoiceT1';
import { ANCIENT_ARMORY_T2_DEFINITION } from './events/ancientArmoryT2';
import { RESTFUL_SHRINE_T2_DEFINITION } from './events/restfulShrineT2';
import { EERIE_SOUNDS_TIER2_DEFINITION } from './events/eerieSoundsT2';
import { OLD_MAP_T2_DEFINITION } from './events/oldMapT2';
import { MYSTERIOUS_PEDESTAL_T2_DEFINITION } from './events/mysteriousPedestalT2';
import { SHRINE_OF_GREATER_EMPOWERMENT_T2_DEFINITION } from './events/shrineOfGreaterEmpowermentT2';

export const DUNGEON_EVENT_DEFINITIONS: Record<string, DungeonEventDefinition> = {
  'SHRINE_OF_EMPOWERMENT_T1': SHRINE_OF_EMPOWERMENT_T1_DEFINITION,
  'HIDDEN_CACHE_TIER1': HIDDEN_CACHE_TIER1_DEFINITION,
  'EERIE_SOUNDS_TIER1': EERIE_SOUNDS_TIER1_DEFINITION,
  'OLD_DIARY_TIER1': OLD_DIARY_TIER1_DEFINITION,
  'FOUNTAIN_OF_CHOICE_T1': FOUNTAIN_OF_CHOICE_T1_DEFINITION,
  'ANCIENT_ARMORY_T2': ANCIENT_ARMORY_T2_DEFINITION,
  'RESTFUL_SHRINE_T2': RESTFUL_SHRINE_T2_DEFINITION,
  'EERIE_SOUNDS_TIER2': EERIE_SOUNDS_TIER2_DEFINITION,
  'OLD_MAP_T2': OLD_MAP_T2_DEFINITION,
  'MYSTERIOUS_PEDESTAL_T2': MYSTERIOUS_PEDESTAL_T2_DEFINITION,
  'SHRINE_OF_GREATER_EMPOWERMENT_T2': SHRINE_OF_GREATER_EMPOWERMENT_T2_DEFINITION,
};
